name: pylife
dependencies:
- python >2
- numpy
- pytest
- pytest-cov
- flake8
- pep8-naming
- scipy
- pandas
- spyder
- cython
- matplotlib
- pymc3
- jupyter
- pip = 20.2
- pip:
  - mystic
  - tables
